services:
  simulator:
    build:
      context: ./
      dockerfile: deploy/docker/Dockerfile
    container_name: sts-simulator
    environment:
      TZ: Europe/Prague
      LOG_FORMAT: json
      LOG_LEVEL: debug
    networks:
      - sts-network
    restart: unless-stopped

networks:
  sts-network:
    driver: bridge